name: Fetch Carris Metropolitana Stops

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch stops data
        run: curl -s https://api.carrismetropolitana.pt/v2/stops > stops.json

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Upload to Databricks Volume
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks fs cp --overwrite stops.json "dbfs:/Volumes/trips_carris_metropolitana/bronze/stops/stops.json"
